### ISSUE TITLE
Kali linux 2022

### ISSUE THREAD

**Issue by gattoconiglio** [owerdogan/whoami-project#29]
Hi, I have encountered some problems:
Windows 10 laptop PC configuration, kali Linux 2022 on virtualbox.
After installing as per procedure the application on my virtual machine (kali 2022.1) and selecting all available modules, everything works perfectly. At some point the connection broke in the browser; moment I noticed that in the terminal there was no longer Kali@Kali: but Kali@windows7...: all normal I thought (it is part of the Hostname module ). So just to try I tried to reconfigure the hostname with the following command: sudo nano /etc/hostname.....at that moment it gave me an error (which I don't have now because I had to delete the virtual machine , and I forgot to take a picture) not allowing me to access the root anymore. Even trying to restart the virtual machine the problem persisted. I tried to do a fix in the application , but it could only be done with sudo. So I basically lost root.
Installed on kali version 2022.2 , this time I entered a new password to access the root, leaving out the default one (kali) So again everything worked and again changed thehostname from kali@kali to kali@McOsX....terminato to use the program attempted a fix but nothing changed i.e. the hostname did not return to default as before. Help, advice ? Implement the possibility to return to the initial configuration ? Thanks

**Comment by WhiteHatCyberus** [comment]
refer to this:
https://github.com/owerdogan/whoami-project/issues/33
