### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by JawadIbrahim** [owerdogan/whoami-project#30]
**Describe the bug**
i have clone it in "root@ibrahim:/home/jawad# " and type this sudo make install
then enter,, it's showing this "make: *** No rule to make target 'install'.  Stop."

**To Reproduce** (This makes bug detection easier.)
1. Go to 'root@ibrahim:/home/jawad# '
2. downloaded all dependencies
3. Clone the repo in /home/jawad
4. cd kali-whoami
5.  where kali-whoami was cloned i entered sudo make install
6. See error (install -m 755 kali-whoami /usr/bin
mkdir -p /usr/share/kali-whoami/backups
cp -vr assets /usr/share/kali-whoami
'assets/icons/kali-whoami.png' -> '/usr/share/kali-whoami/assets/icons/kali-whoami.png'
'assets/kali-whoami.desktop' -> '/usr/share/kali-whoami/assets/kali-whoami.desktop'
'assets/scripts/anti_cold_boot' -> '/usr/share/kali-whoami/assets/scripts/anti_cold_boot'
'assets/scripts/anti_mitm' -> '/usr/share/kali-whoami/assets/scripts/anti_mitm'
'assets/scripts/browser_anonymization' -> '/usr/share/kali-whoami/assets/scripts/browser_anonymization'
'assets/scripts/dns_changer' -> '/usr/share/kali-whoami/assets/scripts/dns_changer'
'assets/scripts/fix' -> '/usr/share/kali-whoami/assets/scripts/fix'
'assets/scripts/hostname_changer' -> '/usr/share/kali-whoami/assets/scripts/hostname_changer'
'assets/scripts/ip_changer' -> '/usr/share/kali-whoami/assets/scripts/ip_changer'
'assets/scripts/log_killer' -> '/usr/share/kali-whoami/assets/scripts/log_killer'
'assets/scripts/mac_changer' -> '/usr/share/kali-whoami/assets/scripts/mac_changer'
'assets/scripts/timezone_changer' -> '/usr/share/kali-whoami/assets/scripts/timezone_changer'
'assets/sources/config' -> '/usr/share/kali-whoami/assets/sources/config'
'assets/sources/whoami.js' -> '/usr/share/kali-whoami/assets/sources/whoami.js'
cp -vr  /usr/share/kali-whoami/assets/kali-whoami.desktop /usr/share/kali-menu/applications/
'/usr/share/kali-whoami/assets/kali-whoami.desktop' -> '/usr/share/kali-menu/applications/'
cp: cannot create regular file '/usr/share/kali-menu/applications/': No such file or directory
make: *** [Makefile:11: install] Error 1
)

i think it's directory problem.

**Screenshots**
![Screenshot from 2022-06-28 17-26-19](https://user-images.githubusercontent.com/67703122/176167591-021f8442-6a7e-474b-8803-458ffa7dafd0.png)

**Please complete the following information:**
 - OS: Ubuntu 20.04.4 LTS
 - Tool version Kali whoami v1.0 release

**Comment by Idlefase** [comment]
usr/share/kali-menu/applications

Dude. Its a script for kali linux since the dir states kali-menu. 

Besides the very point that all software should come from apt in Kali and this one  isn't supported. 

Cheers.

**Comment by owerdogan** [comment]
Soon there will be no such problem. Thank you for your patience <3

**Comment by ChrisCross1337** [comment]
Howdy! Might be a bit late to the party here but you can go ahead and edit the make file (line 11) from :
	cp -vr  $(src_dir)/$(tool_name)/assets/kali-whoami.desktop /usr/share/kali-menu/applications/


to

	cp -vr  $(src_dir)/$(tool_name)/assets/kali-whoami.desktop /usr/share/ubuntu-wayland/applications/

save and re-run `sudo make install`
	
This should install without a problem. Let me know if this helps you out
