### ISSUE TITLE
kali linux wifi adapter TP-link AC1300 Archer T4U V3.20

### ISSUE THREAD

**Issue by Hamed9526** [owerdogan/whoami-project#31]
hello everyone.
I'm new to linux and I installed kali linux 2022.2 on VM. I tried for three days to get the adapter drive for TP-link AC1300 Archer T4U V3.20 and I found nothing in the internet. I followed the instructions in TP-link site but nothing works for me. if anyone could help to solve this problem please put ur solution.

**Comment by Idlefase** [comment]
This is not the place for general support. All issues resolve around the repo.

Besides all information around kali should be followed by the official docs on their site, not a third party. 

Good luck.

**Comment by WhiteHatCyberus** [comment]
honestly such a irrelevant question to ask in this repo, if you're starting out in Linux, especially for general purposes, i would recommend using Fedora or Ubuntu. Kali Linux isnt made for general purposes eventhough you can still use it, its primarily for cybersecurity analysts and penetration testers. 
Concerning the tp link issue, virtual machine will not read your network usb drive from your primary system unless and until you change the network connection type in your virtual machine from NAT to Bridged within the VM settings.
Answering to @Idlefase 's concern, its very true. 
https://www.kali.org/get-kali/#kali-installer-images
