### ISSUE TITLE
How restore original hostname?

### ISSUE THREAD

**Issue by sharifulgeo** [owerdogan/whoami-project#33]
I just used this package to rename host name of my kali(in vmware) but the problem is when I change the hostname using kali-whoami
then many of my commands do not execute since the original host name is changed. I get message like
`msf6 > sudo db_nmap -p1-300 10.23.13.10 -A -sV -O -oA db.nscan`
`sudo: unable to resolve host macOS11: Name or service not known`

Now how can I restore the original hostname?

**Comment by owerdogan** [comment]
sudo echo kali  > /etc/hostname

**Comment by WhiteHatCyberus** [comment]
hostnamectl set-hostname <new_hostname>

**Comment by WhiteHatCyberus** [comment]
if you perhaps encounter a hostname not configured error,
type the following in your distro's terminal:
cd /etc
sudo nano hosts
within the text file add the following line:
<new_hostname> 127.0.0.1
