### ISSUE TITLE
“No file or directory to make target install Stop”

### ISSUE THREAD

**Issue by Berlin155** [owerdogan/whoami-project#43]
Hi, after downloading what I need to use the whoami tool, at “sudo make install” I receive the following text “ No file or directory to make target install Stop” I need to say that I use Parrot os. 
![IMG_5049](https://github.com/owerdogan/whoami-project/assets/128404460/195b8772-437a-4f6d-bae4-748a80d16983)
![IMG_4882](https://github.com/owerdogan/whoami-project/assets/128404460/e0ca17aa-a588-4812-a18f-0829556cb69f)
I’ve done this on a virtual machine 
This happened to me also in Kali Linux

**Comment by jbar2797** [comment]
> Hi, after downloading what I need to use the whoami tool, at “sudo make install” I receive the following text “ No file or directory to make target install Stop” I need to say that I use Parrot os. ![IMG_5049](https://user-images.githubusercontent.com/128404460/255209992-195b8772-437a-4f6d-bae4-748a80d16983.jpeg) ![IMG_4882](https://user-images.githubusercontent.com/128404460/255210012-e0ca17aa-a588-4812-a18f-0829556cb69f.jpeg) I’ve done this on a virtual machine This happened to me also in Kali Linux

you need to cd to the kali-whoami after you clone it

run the "sudo make install" from within the kali-whoami" folder. 

hope that helps

**Comment by Berlin155** [comment]
Yes, it helped. Thanks
