### ISSUE TITLE
stays on the start page where it asks me to subsbcribe 

### ISSUE THREAD

**Issue by funky-tree** [owerdogan/whoami-project#45]
after it asks me to subscribe to the YouTube channel (that doesn't exist), i close the firefox tab, but it just stays on the same screen forever. please either make a youtube channel or remove the screen entirely.

![Screenshot_20230728_234418](https://github.com/owerdogan/whoami-project/assets/110597575/72c45fc9-63d8-4ed6-a0cb-aad9b8a32c39)

**Comment by lightdark00** [comment]
just wait for a lil bit . it will load

**Comment by funky-tree** [comment]
it stays on a 404 not found. i have sometimes waited for 20 minutes because i forgot it in the background. it ain't loading.

**Comment by owerdogan** [comment]
Sorry for this bug, hotfix coming soon...
