### ISSUE TITLE
Dependencies on Kali-menu

### ISSUE THREAD

**Issue by OkulusDev** [owerdogan/whoami-project#52]
When installing a project, you have to create extra directories if the user's operating system is not Kali Linux. And it's not even automated scripts, you have to manually create directories.
I would like to see multidistribution. So that if the system is not kali linux, there are no actions that are created for kali linux.

**Comment by owerdogan** [comment]
Actually, the project in my local workspace is much more advanced than the current version, but it couldn't be completed (due to lack of time). I am working on it again these days, hoping that this time it will be a complete enough version to be published.

**Comment by OkulusDev** [comment]
I close with issue. You can simply create the necessary directories, or edit the installation script a little. Thanks for the project!
